spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://221.203.29.43:3306/clt-ms?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: Dada312!
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 6000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x'

  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 9     # 连接池中的最大空闲连接
        min-idle: 1     # 连接池中的最小空闲连接